services:
  mvg-observer:
    image: ghcr.io/flipez/mvg.observer:latest
    network_mode: host
    environment:
      - CLICKHOUSE_HOST=clickhouse.auch.cool
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_DATABASE=mvg
      - CLICKHOUSE_USERNAME=mvgobserver
      - CLICKHOUSE_PASSWORD=
      - REDIS_ADDR=127.0.0.1:6379
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/health",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 40s
