name: E2E Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/e2e-tests.yml'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/e2e-tests.yml'

jobs:
  e2e-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"
        cache-dependency-path: frontend/pnpm-lock.yaml
        
    - name: Install dependencies
      working-directory: ./frontend
      run: pnpm install --frozen-lockfile
      
    - name: Install Playwright Browsers
      working-directory: ./frontend
      run: pnpm exec playwright install --with-deps
      
    - name: Build frontend
      working-directory: ./frontend
      run: pnpm build
      
    - name: Run Playwright tests
      working-directory: ./frontend
      run: pnpm test:e2e
      env:
        CI: true
        
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: frontend/playwright-report/
        retention-days: 30
        
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-traces
        path: frontend/test-results/
        retention-days: 7