name: E2E Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/e2e-tests.yml'
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/e2e-tests.yml'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install frontend dependencies
        run: |
          cd frontend
          pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: |
          cd frontend
          pnpm exec playwright install chromium

      - name: Build frontend
        run: |
          cd frontend
          pnpm build

      - name: Start dev server in background
        run: |
          cd frontend
          pnpm dev &
          echo $! > dev-server.pid
        env:
          CI: true

      - name: Wait for dev server to be ready
        run: |
          cd frontend
          timeout 60 bash -c 'until curl -s http://localhost:5173 > /dev/null; do sleep 1; done'
        env:
          CI: true

      - name: Run E2E tests
        run: |
          cd frontend
          pnpm test:e2e:no-server
        env:
          CI: true

      - name: Stop dev server
        if: always()
        run: |
          cd frontend
          if [ -f dev-server.pid ]; then
            kill $(cat dev-server.pid) || true
            rm dev-server.pid
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 7

      - name: Upload test traces
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-traces
          path: frontend/test-results/
          retention-days: 7