name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install frontend dependencies
        run: |
          cd frontend
          pnpm install --frozen-lockfile

      - name: Build frontend
        run: |
          cd frontend
          pnpm build

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          cache-dependency-path: backend/go.sum

      - name: Test Go build
        run: |
          cp -r frontend/build backend/
          cd backend
          go build -o mvg-observer .

      - name: Run Go tests
        run: |
          cd backend
          go test ./...

      - name: Test Docker build
        run: |
          docker build -t mvg-observer:test .
